import React from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { X, CheckCircle2, TrendingUp, DollarSign, Download, Printer } from 'lucide-react';

interface BusinessReportModalProps {
    product: any;
    analysis: any;
    isOpen: boolean;
    onClose: () => void;
}

const BusinessReportModal: React.FC<BusinessReportModalProps> = ({ product, analysis, isOpen, onClose }) => {
    if (!isOpen) return null;

    const handlePrint = () => {
        window.print();
    };

    return (
        <AnimatePresence>
            <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 backdrop-blur-sm">
                <motion.div
                    initial={{ opacity: 0, scale: 0.9 }}
                    animate={{ opacity: 1, scale: 1 }}
                    exit={{ opacity: 0, scale: 0.9 }}
                    className="bg-white text-slate-900 w-full max-w-3xl rounded-3xl overflow-hidden shadow-2xl relative max-h-[90vh] overflow-y-auto"
                >
                    <button
                        onClick={onClose}
                        className="absolute top-4 right-4 p-2 bg-slate-100 rounded-full hover:bg-slate-200 transition print:hidden"
                    >
                        <X className="w-5 h-5 text-slate-500" />
                    </button>

                    <div className="p-8 md:p-12 print:p-0">
                        {/* Header */}
                        <div className="flex justify-between items-start mb-10 border-b border-slate-200 pb-8">
                            <div>
                                <div className="text-xs font-bold text-blue-600 uppercase tracking-widest mb-2">
                                    Confidential Business Report
                                </div>
                                <h2 className="text-3xl font-black mb-1">{product.title}</h2>
                                <p className="text-slate-500">Generated by PakPick AI Intelligence Engine</p>
                            </div>
                            <div className="text-right hidden md:block">
                                <div className="text-sm font-bold text-slate-400">Date</div>
                                <div className="font-mono text-slate-700">{new Date().toLocaleDateString()}</div>
                            </div>
                        </div>

                        {/* Executive Summary */}
                        <div className="mb-10 p-6 bg-slate-50 rounded-2xl border border-slate-100">
                            <h3 className="text-lg font-bold mb-4 flex items-center text-slate-800">
                                <CheckCircle2 className="w-5 h-5 mr-2 text-green-500" /> Executive Summary
                            </h3>
                            <p className="text-slate-600 leading-relaxed text-sm">
                                Based on real-time market data, this product shows a <strong>{analysis.sentiment?.label}</strong> level of consumer interest.
                                Our AI calculates a potential profit margin of <strong>{analysis.arbitrage?.margin || '30%+'}</strong> if sourced via {analysis.sourcing?.type}.
                                The recommended strategy is to <strong>{analysis.sourcing?.strategy || 'Direct Import'}</strong> to maximize ROI.
                            </p>
                        </div>

                        {/* Financial Breakdown */}
                        <div className="grid grid-cols-3 gap-6 mb-10">
                            <div className="p-4 border border-slate-200 rounded-xl text-center">
                                <div className="text-slate-400 text-xs uppercase font-bold mb-1">Target Sell Price</div>
                                <div className="text-xl font-bold text-slate-900">PKR {product.price}</div>
                            </div>
                            <div className="p-4 border border-slate-200 rounded-xl text-center bg-blue-50">
                                <div className="text-blue-500 text-xs uppercase font-bold mb-1">Est. Sourcing Cost</div>
                                <div className="text-xl font-bold text-blue-700">Rs. {analysis.arbitrage?.estimated_sourcing_cost || 'N/A'}</div>
                            </div>
                            <div className="p-4 border border-slate-200 rounded-xl text-center bg-green-50">
                                <div className="text-green-500 text-xs uppercase font-bold mb-1">Projected Net Profit</div>
                                <div className="text-xl font-bold text-green-700">Rs. {analysis.arbitrage?.potential_profit || 'N/A'}</div>
                            </div>
                        </div>

                        {/* Market Viability Grid */}
                        <div className="grid md:grid-cols-2 gap-8 mb-10">
                            <div>
                                <h4 className="font-bold text-slate-900 mb-4 flex items-center">
                                    <TrendingUp className="w-4 h-4 mr-2 text-slate-400" /> Market Viability
                                </h4>
                                <ul className="space-y-3">
                                    {(analysis?.checklist || []).map((item: string, i: number) => (
                                        <li key={i} className="flex items-center text-sm text-slate-600">
                                            <div className="w-1.5 h-1.5 bg-green-500 rounded-full mr-3"></div>
                                            {item}
                                        </li>
                                    ))}
                                    <li className="flex items-center text-sm text-slate-600">
                                        <div className="w-1.5 h-1.5 bg-green-500 rounded-full mr-3"></div>
                                        Verified Demand Growth: {analysis.forecast?.monthly_growth_prediction}
                                    </li>
                                </ul>
                            </div>
                            <div>
                                <h4 className="font-bold text-slate-900 mb-4 flex items-center">
                                    <DollarSign className="w-4 h-4 mr-2 text-slate-400" /> Investment Outlook
                                </h4>
                                <div className="space-y-4">
                                    <div className="flex justify-between items-center text-sm border-b border-slate-100 pb-2">
                                        <span className="text-slate-500">Risk Level</span>
                                        <span className="font-bold text-slate-800">{analysis.sentiment?.label === 'High Demand' ? 'Low' : 'Moderate'}</span>
                                    </div>
                                    <div className="flex justify-between items-center text-sm border-b border-slate-100 pb-2">
                                        <span className="text-slate-500">Competition</span>
                                        <span className="font-bold text-slate-800">Medium</span>
                                    </div>
                                    <div className="flex justify-between items-center text-sm border-b border-slate-100 pb-2">
                                        <span className="text-slate-500">Rec. Launch Inventory</span>
                                        <span className="font-bold text-slate-800">50 - 100 Units</span>
                                    </div>
                                </div>
                            </div>
                        </div>

                        {/* Disclaimer */}
                        <div className="text-center pt-8 border-t border-slate-200">
                            <p className="text-[10px] text-slate-400 uppercase tracking-widest mb-6">
                                Generated by PakPick AI • Automated Market Intelligence System
                            </p>

                            <div className="flex items-center justify-center space-x-4 print:hidden">
                                <button
                                    onClick={handlePrint}
                                    className="flex items-center px-6 py-3 bg-slate-900 text-white rounded-xl font-bold hover:bg-slate-800 transition shadow-lg"
                                >
                                    <Printer className="w-4 h-4 mr-2" /> Print / Save PDF
                                </button>
                                <button className="flex items-center px-6 py-3 bg-slate-100 text-slate-600 rounded-xl font-bold hover:bg-slate-200 transition">
                                    <Download className="w-4 h-4 mr-2" /> CSV Data
                                </button>
                            </div>
                        </div>
                    </div>
                </motion.div>
            </div>
        </AnimatePresence>
    );
};

export default BusinessReportModal;
